name: SonarCloud

on:
  push:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pastikan clone secara penuh untuk analisis yang lebih relevan

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Sesuaikan versi Node.js sesuai kebutuhan proyek Anda

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build  # Hapus atau ubah langkah ini jika tidak ada script build

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx sonar-scanner
